sudo: required
services:
  - docker

before_install:
  - docker build -t adek676/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adek676/react-test npm test

after_success:
  - docker build -t adek676/multi-client ./client
  - docker build -t adek676/multi-nginx ./nginx
  - docker build -t adek676/multi-server ./server
  - docker build -g adek676/multi-worker ./worker